services:
  - type: web
    name: pleinair-club-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false  # нужно установить вручную в настройках Render
      - key: RENDER
        value: true
    healthCheckPath: /health
    autoDeploy: true